name = "TensorsLite"
uuid = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Zeros = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
