name = "TensorsLite"
uuid = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Zeros = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"

[weakdeps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[extensions]
LinearAlgebraExt = "LinearAlgebra"
SIMDExt = "SIMD"

[compat]
Zeros = "0.3"
julia = "1.10"
SIMD = "3.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[targets]
test = ["Test", "LinearAlgebra", "SIMD"]
